# kinematic: two_wheel_steering
type: 1FAS2RWD
geometry:
  # axles_distance: 1.507
  axles_distance: 1.548 # 1.507 + 0.041
  front_axle:
    wheels_distance: 1.016 # To be checked
    wheels:
      radius: 0.20 # To be checked
      width: 0.09 # To be checked
      x_offset: -0.041 # must me change forward/inverse kinematic to compute correct front wheel speed in simulation
      hub_carrier_offset: 0.07 # To be checked
  rear_axle:
    wheels_distance: 1.128
    wheels:
      radius: 0.285
      width: 0.112
      hub_carrier_offset: 0.0
  aabb:
    length: 2.111
    width: 1.0 # To be configured
    height: 0.25 # To be configured
    center: [0., 0., 0.780] # To be configured
  ground_clearance: 0.655

front_axle_steering_control:
  command:
    maximal_angle: 0.5760 # To be configured
    maximal_angular_speed: 0.2433 # To be configured
  sensor:
    angle_std: 0.008722 # To be configured
    angle_range: 0.5760 # To be configured

rear_wheels_speed_control:
  command:
    maximal_speed: 1.0 # To be configured
    maximal_acceleration: 1.0 # To be configured
  sensor:
    speed_std: 0.1 # To be configured
    speed_range: 1.0 # To be configured

inertia:
  mass: 800. # To be configured
  center: [-0.1, 0.0, 0.2] # To be configured
  z_moment: 0. # To be configured

control_point: [-0.7535, 0.0, 0.0]

joints:
  base_footprint_joint_name: base_footprint_joint
  inertial_joint_name: initial_joint
  front_axle_steering_joint_name: front_axle_steering_joint
  front_left_wheel_steering_joint_name: front_left_wheel_steering_joint
  front_right_wheel_steering_joint_name: front_right_wheel_steering_joint
  front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
  front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
  rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
  rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: initial_link
  front_axle_steering_link_name: front_axle_steering_link
  front_left_wheel_steering_link_name: front_left_wheel_steering_link
  front_right_wheel_steering_link_name: front_right_wheel_steering_link
  front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
  front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
  rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
  rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link
