# kinematic: two_wheel_steering
type: 2FWS2RWD
geometry:
  axles_distance: 2.0                # To be configured
  front_axle:
    wheels_distance: 1.5             # To be configured
    wheels:
      radius: 0.32                   # To be configured
      width: 0.2                     # To be configured
      hub_carrier_offset: 0.02       # To be configured 
  rear_axle:
    wheels_distance: 1.5             # To be configured
    wheels:
      radius: 0.54                   # To be configured
      width: 0.25                    # To be configured
      hub_carrier_offset: 0.02       # To be configured
  aabb:
    length: 2.4                      # To be configured
    width: 1.0                       # To be configured
    height: 1.0                      # To be configured
    center: [0., 0., 1.0]            # To be configured
  ground_clearance: 0.15             # To be configured

front_wheels_steering_control:
    command:
      maximal_angle: 0.73            # To be configured
      maximal_angular_speed: 0.2433  # To be configured
    sensor:
      angle_std: 0.017453            # To be configured
      angle_range: 0.73              # To be configured

rear_wheels_speed_control:
    command:
      maximal_speed: 3.0             # To be configured
      maximal_acceleration: 1.0      # To be configured
    sensor:
      speed_std: 0.1                 # To be configured
      speed_range: 3.0               # To be configured

inertia:
  mass: 800.                         # To be configured 
  center: [-0.1, 0.0, 0.2]           # To be configured
  z_moment: 0.                       # To be configured

control_point: [-1.0, 0.0, 0.0]      # To be configured 

joints:
  base_footprint_joint_name: base_footprint_joint
  inertial_joint_name: initial_joint
  front_left_wheel_steering_joint_name: front_left_wheel_steering_joint
  front_right_wheel_steering_joint_name: front_right_wheel_steering_joint
  front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
  front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
  rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
  rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: initial_link
  front_left_wheel_steering_link_name: front_left_wheel_steering_link
  front_right_wheel_steering_link_name: front_right_wheel_steering_link
  front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
  front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
  rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
  rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link

