<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <visual>
            <origin xyz="0 0 ${chassis_height-0.1}" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://cinteo_description/meshes/chasis_cinteo.stl"
                    scale="0.001 0.001 0.001" />
            </geometry>
            <material name=" grey">
                <color rgba=" 0.6 0.6 0.6 1" />
            </material>
            <xacro:green />
        </visual>
    </xacro:macro>


</robot>